SELECT * FROM COMPANY;
SELECT * FROM CUSTOM;
SELECT * FROM POINT;
SELECT * FROM PRODUCT;
SELECT * FROM RESEARCH;
SELECT * FROM SALES;


SELECT * FROM CUSTOM;


SELECT USERNAME, RPAD(SUBSTR(JUMIN,1,8),14,'*') JUMIN FROM CUSTOM;