INSERT INTO EMP_TEMP(EMPNO, ENAME, JOB, MGR, HIREDATE, SAL, COMM, DEPTNO) SELECT E.EMPNO, E.ENAME, E.JOB, E.MGR, E.HIREDATE, E.SAL, E.COMM, E.DEPTNO FROM EMP E, SALGRADE S WHERE E.SAL BETWEEN LOSAL AND HISAL AND S.GRADE = 1;

SELECT * FROM EMP_TEMP;

CREATE TABLE DEPT_TEMP2 AS SELECT * FROM DEPT;

UPDATE DEPT_TEMP2 SET LOC = 'SEOUL';

SELECT * FROM DEPT_TEMP2;

ROLLBACK;

UPDATE DEPT_TEMP2 SET DNAME = 'DATABASE' WHERE DEPTNO = 40;

UPDATE DEPT_TEMP2 SET (DNAME, LOC) = (SELECT DNAME, LOC FROM DEPT WHERE DEPTNO = 40) WHERE DEPTNO = 40;

CREATE TABLE EMP_TEMP2
AS SELECT * FROM EMP;


SELECT * FROM EMP_TEMP2;

DESC EMP;


SELECT DEPTNO FROM DEPT;
SELECT DEPTNO FROM DEPT WHERE DEPTNO = 10;

DESC DEPT;

SELECT DNAME FROM DEPT WHERE NVL((SELECT DNAME FROM DEPT WHERE DEPTNO = 50), '0') = '0';

SELECT DNAME  FROM DEPT WHERE DEPTNO = 50;

CREATE TABLE CHAP10HW_EMP AS SELECT * FROM EMP;

CREATE TABLE CHAP10HW_DEPT AS SELECT * FROM DEPT;

CREATE TABLE CHAP10HW_SALGRADE AS SELECT * FROM SALGRADE;


SELECT * FROM CHAP10HW_DEPT;

INSERT INTO CHAP10HW_DEPT VALUES(50, 'ORACLE', 'BUSAN');
INSERT INTO CHAP10HW_DEPT VALUES(60, 'SQL', 'ILSAN');
INSERT INTO CHAP10HW_DEPT VALUES(70, 'SELECT', 'INCHEON');
INSERT INTO CHAP10HW_DEPT VALUES(80, 'DML', 'BUNDANG');


UPDATE CHAP10HW_DEPT SET DEPTNO = 50 WHERE DNAME = 'ORACLE';

DELETE FROM CHAP10HW_DEPT WHERE DEPTNO = 50;














