-- 연습문제 풀이

--SELECT DEPNO, DNAME, AVG_SAL, MAX_SAL, MIN_SAL, CNT FROM EMP;

--SELECT D.DEPTNO, D.DNAME, AVG(SAL) AVG_SAL, MAX(SAL) MAX_SAL, MIN(SAL) MIN_SAL, COUNT(*) CNT FROM DEPT D, EMP E WHERE DEPTNO <= 30;

--DO IT 239-2번 문제
SELECT D.DEPTNO, D.DNAME, TRUNC(AVG(SAL)) AVG_SAL, MAX(SAL) MAX_SAL, MIN(SAL) MIN_SAL, COUNT(*) CNT FROM DEPT D, EMP E WHERE D.DEPTNO = E.DEPTNO GROUP BY D.DEPTNO, D.DNAME;

SELECT E.ENAME FROM DEPT D, EMP E;

--DO IT 239-3번 문제
SELECT D.DEPTNO, D.DNAME, E.ENAME, E.EMPNO, E.JOB, E.SAL FROM EMP E, DEPT D WHERE E.DEPTNO(+) = D.DEPTNO GROUP BY D.DEPTNO, D.DNAME, E.ENAME, E.EMPNO, E.JOB, E.SAL ORDER BY DEPTNO;

--영운(GROUP BY 삭제: 필요 없었음)
SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.MGR, E.SAL, E.DEPTNO "DEPTNO_1", S.GRADE, S.LOSAL, S.HISAL, M.EMPNO, M.ENAME
FROM EMP E, EMP M, DEPT D, SALGRADE S WHERE D.DEPTNO = E.DEPTNO(+) AND E.MGR = M.EMPNO(+) AND E.SAL BETWEEN S.LOSAL(+) AND S.HISAL(+)
GROUP BY D.DEPTNO, D.DNAME,  E.EMPNO, E.ENAME, E.MGR, E.SAL, E.DEPTNO, S.GRADE, S.LOSAL, S.HISAL, M.EMPNO, M.ENAME ORDER BY D.DEPTNO;

--영운(최종)
SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.MGR, E.SAL, E.DEPTNO "DEPTNO_1", S.GRADE, S.LOSAL, S.HISAL, M.EMPNO, M.ENAME
FROM EMP E, EMP M, DEPT D, SALGRADE S WHERE D.DEPTNO = E.DEPTNO(+) AND E.MGR = M.EMPNO(+) AND E.SAL BETWEEN S.LOSAL(+) AND S.HISAL(+) ORDER BY D.DEPTNO, E.EMPNO;

--시연
SELECT C.DEPTNO,DNAME,A.EMPNO,A.ENAME,A.MGR,A.SAL,A.DEPTNO DEPTNO_1,D.LOSAL,D.HISAL,D.GRADE,A.MGR,B.ENAME
FROM EMP 
A RIGHT OUTER JOIN DEPT C ON A.DEPTNO = C.DEPTNO
LEFT JOIN SALGRADE D ON A.SAL BETWEEN D.LOSAL AND D.HISAL
LEFT JOIN EMP B ON A.MGR = B.EMPNO
ORDER BY C.DEPTNO,A.EMPNO;

-- HAVING E.SAL BETWEEN S.LOSAL AND S.HISAL
-- SAL BETWEEN '1991-09-01' AND '1991-09-30'



--1. EMP 테이블에서 Blake와 같은 부서에 있는 모든 사원의 이름과 입사일자를 출력하는 SELECT문을 작성하시오.
SELECT ENAME, HIREDATE FROM EMP WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME = 'BLAKE');


--2. EMP 테이블에서 평균 급여 이상을 받는 모든 종업원에 대해서 종업원 번호와 이름을 출력하는 SELECT문을 작성하시오. 단 급여가 많은 순으로 출력하여라.
SELECT EMPNO, ENAME, SAL FROM EMP WHERE SAL >= (SELECT AVG(SAL) FROM EMP) ORDER BY SAL DESC;


--3. EMP 테이블에서 이름에 “T”가 있는 사원이 근무하는 부서에서 근무하는 모든 종업원에 대해 사원 번호,이름,급여를 출력하는 SELECT문을 작성하시오. 단 사원번호 순으로 출력하여라.
SELECT EMPNO, ENAME, SAL FROM EMP WHERE ENAME LIKE '%L%' ORDER BY EMPNO;

SELECT EMPNO, ENAME, SAL FROM EMP WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME LIKE '%T%') ORDER BY EMPNO;


--4. EMP 테이블에서 부서 위치가 Dallas인 모든 종업원에 대해 이름,업무,급여를 출력하는 SELECT문을 작성하시오.
SELECT ENAME, JOB, SAL FROM EMP E, DEPT D WHERE E.DEPTNO = D.DEPTNO AND LOC = 'DALLAS';



--5. EMP 테이블에서 King에게 보고하는 모든 사원의 이름과 급여를 출력하는 SELECT문을 작성하시오.
SELECT ENAME, SAL FROM EMP WHERE MGR = (SELECT EMPNO FROM EMP WHERE ENAME = 'KING');



--6. EMP 테이블에서 SALES부서 사원의 이름,업무를 출력하는 SELECT문을 작성하시오.
SELECT E.ENAME, JOB FROM EMP E, DEPT D WHERE E.DEPTNO = D.DEPTNO AND E.DEPTNO = (SELECT DEPTNO FROM DEPT WHERE DNAME = 'SALES');



SELECT * FROM SALGRADE;
SELECT * FROM DEPT;



--7. EMP 테이블에서 월급이 부서 30의 최저 월급보다 높은 사원을 출력하는 SELECT문을 작성하시오.
SELECT * FROM EMP WHERE SAL > (SELECT AVG(SAL) FROM EMP WHERE DEPTNO = 30);


--8. EMP 테이블에서 부서 10에서 부서 30의 사원과 같은 업무를 맡고 있는 사원의 이름과 업무를 출력하는 SELECT문을 작성하시오.

SELECT * FROM EMP WHERE DEPTNO = 10;



--9. EMP 테이블에서 FORD와 업무도 월급도 같은 사원의 모든 정보를 출력하는 SELECT문을 작성하시오.
SELECT * FROM EMP E WHERE (SELECT JOB FROM EMP WHERE ENAME = 'WARD') = JOB AND (SELECT SAL FROM EMP WHERE ENAME = 'WARD') = SAL AND ENAME <> 'WARD';
--FORD는 같은 값이 없어서 있는 WARD로 대체



--10. EMP 테이블에서 업무가 JONES와 같거나 월급이 FORD이상인 사원의 정보를 이름,업무,부서번호,급여를 출력하는 SELECT문을 작성하시오.
-- 단 업무별, 월급이 많은 순으로 출력하여라.

SELECT ENAME, JOB, SAL FROM EMP WHERE (SELECT JOB FROM EMP WHERE ENAME = 'JONES') = JOB AND SAL >= (SELECT SAL FROM EMP WHERE ENAME = 'JAMES') AND ENAME <> 'JONES' ORDER BY JOB, SAL DESC;
--여기도 JONES와 같은 없무에서 FORD보다 더 많은 월급이 없어서 JAMES로 대체



--11. EMP 테이블에서 SCOTT 또는 WARD와 월급이 같은 사원의 정보를 이름,업무,급여를 출력하는 SELECT문을 작성하시오.
SELECT ENAME, JOB, SAL FROM EMP WHERE (SAL = (SELECT SAL FROM EMP WHERE ENAME = 'MARTIN') OR SAL = (SELECT SAL FROM EMP WHERE ENAME = 'FORD')) AND (ENAME <>' MARTIN' OR ENAME <> 'FORD');
--SCOTT이 없음! WARD의 급여와 같은 사람도 없음...
--SCOTT을 MARTIN으로 교체


--(SELECT SAL FROM EMP WHERE LOC = 'CHICAGO')
--12. EMP 테이블에서 CHICAGO에서 근무하는 사원과 같은 업무를 하는 사원의 이름,업무를 출력하는 SELECT문을 작성하시오.
SELECT ENAME, JOB FROM EMP WHERE JOB  IN(SELECT JOB FROM EMP WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE LOC = 'CHICAGO') GROUP BY JOB);


--13. EMP 테이블에서 부서별로 월급이 평균 월급보다 높은 사원을 부서번호,이름,급여를 출력하는 SELECT문을 작성하시오.

SELECT ENAME, JOB FROM EMP WHERE JOB  IN(SELECT JOB FROM EMP WHERE DEPTNO = (SELECT DEPTNO FROM DEPT WHERE LOC = 'CHICAGO') GROUP BY JOB);

SELECT DEPTNO, AVG(SAL) FROM EMP GROUP BY DEPTNO;



SELECT DEPTNO FROM EMP GROUP BY DEPTNO;

SELECT DEPTNO FROM EMP GROUP BY DEPTNO;

SELECT AVG(SAL) FROM EMP GROUP BY DEPTNO;

SELECT EMPNO, ENAME, SAL FROM EMP WHERE (SELECT SAL FROM EMP GROUP BY DEPTNO) > (SELECT AVG(SAL) FROM EMP GROUP BY DEPTNO);-- AND DEPTNO IN((SELECT DEPTNO FROM EMP GROUP BY DEPTNO));



--14. EMP 테이블에서 업무별로 월급이 평균 월급보다 낮은 사원을 부서번호,이름,급여를 출력하는 SELECT문을 작성하시오.
--
--
-- 
--
-- 
--
--15. EMP 테이블에서 적어도 한명 이상으로부터 보고를 받을 수 있는 사원을 업무,이름,사원번호,부서번호를 출력하는 SELECT문을 작성하시오.
--
-- 
--
-- 
--
--16. EMP 테이블에서 말단 사원의 사원번호,이름,업무,부서번호를 출력하는 SELECT문을 작성하시오.












