-- 연습문제 풀이

--SELECT DEPNO, DNAME, AVG_SAL, MAX_SAL, MIN_SAL, CNT FROM EMP;

--SELECT D.DEPTNO, D.DNAME, AVG(SAL) AVG_SAL, MAX(SAL) MAX_SAL, MIN(SAL) MIN_SAL, COUNT(*) CNT FROM DEPT D, EMP E WHERE DEPTNO <= 30;

--DO IT 239-2번 문제
SELECT D.DEPTNO, D.DNAME, TRUNC(AVG(SAL)) AVG_SAL, MAX(SAL) MAX_SAL, MIN(SAL) MIN_SAL, COUNT(*) CNT FROM DEPT D, EMP E WHERE D.DEPTNO = E.DEPTNO GROUP BY D.DEPTNO, D.DNAME;

SELECT E.ENAME FROM DEPT D, EMP E;

--DO IT 239-3번 문제
SELECT D.DEPTNO, D.DNAME, E.ENAME, E.EMPNO, E.JOB, E.SAL FROM EMP E, DEPT D WHERE E.DEPTNO(+) = D.DEPTNO GROUP BY D.DEPTNO, D.DNAME, E.ENAME, E.EMPNO, E.JOB, E.SAL ORDER BY DEPTNO;



SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.MGR, E.SAL, E.DEPTNO "DEPTNO_1", S.LOSAL, S.HISAL, S.GRADE
FROM EMP E, EMP M, DEPT D, SALGRADE S WHERE E.DEPTNO(+) = D.DEPTNO AND E.SAL IN(BETWEEN(S.LOSAL, S.HISAL), 0)
GROUP BY D.DEPTNO, D.DNAME,  E.EMPNO, E.ENAME, E.MGR, E.SAL, E.DEPTNO, S.LOSAL, S.HISAL, S.GRADE ORDER BY D.DEPTNO;


SELECT D.DEPTNO, D.DNAME, E.EMPNO, E.ENAME, E.MGR, E.SAL, E.DEPTNO "DEPTNO_1", S.LOSAL, S.HISAL, S.GRADE
FROM EMP E, EMP M, DEPT D, SALGRADE S WHERE E.DEPTNO(+) = D.DEPTNO AND E.SAL BETWEEN S.LOSAL AND S.HISAL
GROUP BY D.DEPTNO, D.DNAME,  E.EMPNO, E.ENAME, E.MGR, E.SAL, E.DEPTNO, S.LOSAL, S.HISAL, S.GRADE ORDER BY D.DEPTNO;

-- SAL BETWEEN '1991-09-01' AND '1991-09-30'
 
SELECT SAL, S.LOSAL, S.HISAL FROM EMP E, SALGRADE S WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL;

SELECT * FROM EMP;

SELECT * FROM DEPT;

SELECT * FROM SALGRADE;








